# Generated by Django 4.2.11 on 2024-09-19 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_count', models.IntegerField(default=-1)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
