# Generated by Django 4.2.11 on 2024-11-11 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerLxcImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=150)),
                ('architecture', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContainerLxcList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('cpu_usage', models.FloatField(default=0)),
                ('ram_usage', models.FloatField(default=0)),
                ('disk_usage', models.FloatField(default=0)),
                ('uptime', models.IntegerField(default=0)),
                ('processes', models.IntegerField(default=0)),
                ('requests_c', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostCurrentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_containers', models.IntegerField(default=0)),
                ('active_connections', models.IntegerField(default=0)),
                ('requests', models.JSONField(blank=True, default=list, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HostDailyMaxMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_containers', models.IntegerField(default=0)),
                ('min_containers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('interface', models.CharField(max_length=30)),
                ('ip_type', models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=4)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='api.containerlxclist')),
            ],
        ),
    ]
