# Generated by Django 4.2.11 on 2024-09-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weekmax_rename_hora_containerstatus_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekmax',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Segunda'), ('Tuesday', 'Terça'), ('Wednesday', 'Quarta'), ('Thursday', 'Quinta'), ('Friday', 'Sexta'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=10, unique=True),
        ),
    ]
