# Generated by Django 4.2.11 on 2024-11-12 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hostcontainersconnections_hostrps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostdailymaxmin',
            name='date',
        ),
        migrations.AddField(
            model_name='hostdailymaxmin',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
