# Generated by Django 4.2.11 on 2024-09-20 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_weekmax_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='weekmax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
