# Generated by Django 4.2.11 on 2024-11-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hostdailymaxmin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='containermetrics',
            name='cpu_usage_check',
            field=models.BooleanField(default=False),
        ),
    ]
