# Generated by Django 4.2.11 on 2024-11-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_containermetrics_cpu_usage_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containermetrics',
            name='cpu_usage_check',
        ),
    ]
