# Generated by Django 4.2.11 on 2024-09-20 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_containerstatus_time_alter_weekmax_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerstatus',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='weekmax',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
