# Generated by Django 4.2.11 on 2024-11-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_containermetrics_cpu_usage_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuUsageControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.BooleanField(default=False)),
                ('last_executed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
