# Generated by Django 4.2.11 on 2024-09-20 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_containerstatus_time_alter_weekmax_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_containers', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
        ),
        migrations.DeleteModel(
            name='WeekMax',
        ),
    ]
