# Generated by Django 4.2.11 on 2024-09-22 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_containerstatus_currentcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('cpu_usage', models.FloatField(default=0)),
                ('ram_usage', models.FloatField(default=0)),
                ('rps', models.IntegerField(default=0)),
                ('uptime', models.IntegerField(default=0)),
                ('http_errors', models.IntegerField(default=0)),
                ('latency', models.FloatField(default=0)),
            ],
        ),
    ]
