# Generated by Django 4.2.11 on 2024-09-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_containermetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMaxMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('max_containers', models.IntegerField(default=0)),
                ('min_containers', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyMax',
        ),
        migrations.DeleteModel(
            name='DailyMin',
        ),
    ]
