# Generated by Django 4.2.11 on 2024-09-24 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dailymaxmin_delete_dailymax_delete_dailymin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymaxmin',
            name='container_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymaxmin',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
