# Generated by Django 4.2.11 on 2024-09-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dailymaxmin_container_count_dailymaxmin_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymaxmin',
            name='container_count',
        ),
        migrations.RemoveField(
            model_name='dailymaxmin',
            name='time',
        ),
    ]
