# Generated by Django 4.2.11 on 2024-09-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_dailymaxmin_container_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containermetrics',
            old_name='container_id',
            new_name='container_name',
        ),
    ]
