# Generated by Django 4.2.11 on 2024-09-25 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_containermetrics_rps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containermetrics',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='currentcount',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
