# Generated by Django 4.2.11 on 2024-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_containermetrics_time_alter_currentcount_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='containermetrics',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
