# Generated by Django 4.2.11 on 2024-09-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_containermetrics_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containermetrics',
            old_name='uptime',
            new_name='update_time',
        ),
    ]
