# Generated by Django 4.2.11 on 2024-09-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_active_connections_containermetrics_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containermetrics',
            old_name='update_time',
            new_name='uptime',
        ),
    ]
