# Generated by Django 4.2.11 on 2024-09-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_update_time_containermetrics_uptime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containermetrics',
            old_name='http_errors',
            new_name='processes',
        ),
        migrations.RenameField(
            model_name='containermetrics',
            old_name='latency',
            new_name='rps',
        ),
    ]
