# Generated by Django 4.2.11 on 2024-10-15 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_containermetrics_rt_containermetrics_urt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerLxcList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('interface', models.CharField(max_length=30)),
                ('ip_type', models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=4)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='api.containerlxclist')),
            ],
        ),
    ]
