# Generated by Django 4.2.11 on 2024-11-08 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_containerlxclist_containerip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerLxcImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=150)),
                ('architecture', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('upload_date', models.CharField(max_length=50)),
            ],
        ),
    ]
