# Generated by Django 4.2.11 on 2024-11-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_containerlxcimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerlxcimage',
            name='type',
        ),
    ]
