# Generated by Django 4.2.11 on 2024-11-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_containerlxcimage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerlxcimage',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
