# Generated by Django 4.2.11 on 2024-09-16 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerstatus',
            name='active_containers',
        ),
        migrations.RemoveField(
            model_name='containerstatus',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='containerstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='containerstatus',
            name='container_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='containerstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
