# Generated by Django 4.2.11 on 2024-09-16 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('containers', '0002_remove_containerstatus_active_containers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstatus',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='containerstatus',
            name='container_count',
            field=models.IntegerField(default=0),
        ),
    ]
