# Generated by Django 4.2.11 on 2024-09-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_containerstatus_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerstatus',
            name='user',
        ),
    ]
