# Generated by Django 4.2.11 on 2024-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_remove_containerstatus_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerstatus',
            old_name='container_count',
            new_name='active_containers',
        ),
        migrations.RemoveField(
            model_name='containerstatus',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='containerstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
