# Generated by Django 4.2.11 on 2024-09-17 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_rename_container_count_containerstatus_active_containers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerstatus',
            name='active_containers',
        ),
        migrations.RemoveField(
            model_name='containerstatus',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='containerstatus',
            name='container_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='containerstatus',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
