# Generated by Django 4.2.11 on 2024-09-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_remove_containerstatus_active_containers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerstatus',
            old_name='timestamp',
            new_name='hora',
        ),
    ]
